version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: shop_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-shop}
    ports:
      - "5433:5432"
    volumes:
      - shop_postgres_data:/var/lib/postgresql/data

volumes:
  shop_postgres_data:
